# Generated by Django 6.0 on 2025-12-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
