# Generated by Django 6.0 on 2026-05-18 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0005_backfill_team_soft_delete_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', 'status', 'is_deleted'], name='projects_pr_team_id_7b2d71_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_deleted', 'created_at'], name='projects_pr_is_dele_bf1625_idx'),
        ),
    ]
