version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=taskhive
      - POSTGRES_USER=emp
      - POSTGRES_PASSWORD=12345
    ports:
      - "5433:5432"

  redis:
    image: redis:8.6
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=taskhive
      - MINIO_ROOT_PASSWORD=taskhive-secret
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  web:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=task_hive.settings.prod
      - DATABASE_URL=postgres://emp:12345@db:5432/taskhive
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - USE_S3_STORAGE=True
      - AWS_ACCESS_KEY_ID=taskhive
      - AWS_SECRET_ACCESS_KEY=taskhive-secret
      - AWS_STORAGE_BUCKET_NAME=taskhive
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_ADDRESSING_STYLE=path
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
  worker:
    build: .
    command: celery -A task_hive worker --loglevel=info
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=task_hive.settings.prod
      - DATABASE_URL=postgres://emp:12345@db:5432/taskhive
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - USE_S3_STORAGE=True
      - AWS_ACCESS_KEY_ID=taskhive
      - AWS_SECRET_ACCESS_KEY=taskhive-secret
      - AWS_STORAGE_BUCKET_NAME=taskhive
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_ADDRESSING_STYLE=path
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - minio

volumes:
  postgres_data:
  static_volume:
  minio_data: