# Generated by Django 6.0 on 2026-05-18 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_deleted_at_project_deleted_by_and_more'),
        ('tasks', '0001_initial'),
        ('teams', '0005_backfill_team_soft_delete_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='teams.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.tag'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status', 'is_deleted'], name='tasks_task_project_e8cf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'assignee', 'is_deleted'], name='tasks_task_project_c43abb_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent', 'is_deleted'], name='tasks_task_parent__fbed7c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_deleted', 'updated_at'], name='tasks_task_is_dele_a05af0_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['team', 'project', 'name'], name='tasks_tag_team_id_2707fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('project', 'name')},
        ),
    ]
